package db2

import (
	"context"
	"fmt"
	"strings"
	"sync"
	"testing"
	"time"

	"github.com/apache/arrow-go/v18/arrow"
	"github.com/datazip-inc/olake/tests/testutils"
	_ "github.com/ibmdb/go_ibm_db"
	"github.com/jmoiron/sqlx"
	"github.com/stretchr/testify/require"
)

var (
	dbConnsMu sync.Mutex
	dbConns   = map[string]*sqlx.DB{}
)

// buildDSN builds the go_ibm_db DSN from source.json. It mirrors the db2 driver's own DSN
// construction so the tests connect exactly the way the driver does.
func buildDSN(config testutils.SourceConfig) string {
	dsn := fmt.Sprintf(
		"HOSTNAME=%s;PORT=%d;DATABASE=%s;UID=%s;PWD=%s;",
		config.String("host"),
		config.Int("port"),
		config.String("database"),
		config.String("username"),
		config.String("password"),
	)

	// JDBC-style params if provided
	for key, value := range config.StringMap("jdbc_url_params") {
		dsn += fmt.Sprintf(";%s=%s", key, value)
	}

	// SSL if enabled
	if ssl := config.Sub("ssl"); ssl != nil && ssl.String("mode") != "disable" {
		dsn += ";SECURITY=SSL"
	}

	return dsn
}

func getDB(ctx context.Context, t *testing.T, dsn string) *sqlx.DB {
	t.Helper()

	dbConnsMu.Lock()
	defer dbConnsMu.Unlock()
	if db, ok := dbConns[dsn]; ok {
		return db
	}
	db, err := sqlx.ConnectContext(ctx, "go_ibm_db", dsn)
	require.NoError(t, err, "failed to connect to db2")
	dbConns[dsn] = db
	return db
}

// exec runs one autocommit statement, retrying only the DB2 deadlock victim (SQL0911N,
// SQLSTATE 40001): TestDB2Sync and TestDB22PC run in parallel and their DDL contends
// on the system catalog, so either side can be rolled back and has to replay the statement.
func exec(ctx context.Context, db *sqlx.DB, query string) error {
	var err error
	for attempt := range 3 {
		if _, err = db.ExecContext(ctx, query); err == nil || !strings.Contains(err.Error(), "SQLSTATE=40001") {
			return err
		}
		select {
		case <-ctx.Done():
			return ctx.Err()
		case <-time.After(time.Duration(attempt+1) * time.Second):
		}
	}
	return err
}

func ExecuteQuery(ctx context.Context, t *testing.T, conf *testutils.TestConfig, operation string) {
	t.Helper()

	var dsn string
	if conf.SourceBaseConfig != nil {
		dsn = buildDSN(conf.SourceBaseConfig)
	} else {
		dsn = "HOSTNAME=localhost;PORT=50000;DATABASE=testdb;UID=db2inst1;PWD=secret1234;"
	}

	db := getDB(ctx, t, dsn)
	var err error

	integrationTestTable := testutils.TestTableName(conf)
	var query string

	switch operation {
	case "drop-all":
		query = `
			BEGIN
				FOR t AS SELECT TABNAME FROM SYSCAT.TABLES WHERE TYPE = 'T' AND TABSCHEMA = CURRENT SCHEMA DO
					EXECUTE IMMEDIATE 'DROP TABLE "' || t.TABNAME || '"';
				END FOR;
			END`

	case "create":
		query = fmt.Sprintf(`
			CREATE TABLE %s (
				id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				col_cursor BIGINT,
				col_bigint BIGINT,
				col_char CHAR(1),
				col_character CHAR(10),
				col_varchar VARCHAR(50),
				col_date DATE,
				col_decimal DECIMAL(10, 2),
				col_decfloat DECFLOAT,
				col_double DOUBLE,
				col_real REAL,
				col_int INTEGER,
				col_smallint SMALLINT,
				col_bool BOOLEAN,
				col_clob CLOB(1M),
				col_blob BLOB(1M),
				col_timestamp TIMESTAMP,
				col_time TIME,
				col_graphic GRAPHIC(11),
				col_vargraphic VARGRAPHIC(14),
				excludedColumn INT NULL
			)`, integrationTestTable)
		// DB2 has no CREATE TABLE IF NOT EXISTS; tolerate an existing table (SQL0601N,
		// SQLSTATE 42710) to match the other drivers' create semantics.
		if cerr := exec(ctx, db, query); cerr != nil && !strings.Contains(cerr.Error(), "SQL0601N") {
			require.NoError(t, cerr, "Failed to execute create operation")
		}
		requireEmptyTable(ctx, t, db, integrationTestTable, operation)
		return

	case "drop":
		err = exec(ctx, db, fmt.Sprintf(`DROP TABLE %s`, integrationTestTable))
		if err != nil && !strings.Contains(err.Error(), "SQL0204N") {
			require.NoError(t, err, "failed to drop %s", integrationTestTable)
		}
		return

	case "clean":
		query = fmt.Sprintf("DELETE FROM %s", integrationTestTable)

	case "add":
		insertTestData(ctx, t, db, integrationTestTable)
		return

	case "insert":
		query = fmt.Sprintf(`
			INSERT INTO %s (
				col_cursor, col_bigint, col_char, col_character,
				col_varchar, col_date, col_decimal, col_decfloat,
				col_double, col_real, col_int, col_smallint,
				col_clob, col_blob, col_timestamp, col_time,
				col_graphic, col_vargraphic, col_bool, excludedColumn
			) VALUES (
				6, 12345678901234, 'c', 'char_val',
				'varchar_val', DATE('2023-01-01'), 123.45, 123.45,
				123.456789, 123.5, 123, 123,
				CLOB('sample text'), BLOB(X'424C4F422044415441204F4E45'),
				TIMESTAMP('2023-01-01-12.00.00.000000'),
				TIME('12.00.00'),
				GRAPHIC('graphic_val'),
				VARGRAPHIC('vargraphic_val'),
				TRUE,
				101
			)`, integrationTestTable)
		err = exec(ctx, db, query)
		require.NoError(t, err, "Failed to execute %s operation", operation)
		// insert a filtered row — timestamp is before the filter threshold, so it won't be synced
		filteredQuery := fmt.Sprintf(`
			INSERT INTO %s (
				col_cursor, col_bigint, col_char, col_character,
				col_varchar, col_date, col_decimal, col_decfloat,
				col_double, col_real, col_int, col_smallint,
				col_clob, col_blob, col_timestamp, col_time,
				col_graphic, col_vargraphic, col_bool, excludedColumn
			) VALUES (
				-1, 111111111111111, 'x', 'filtered',
				'filtered_val', DATE('2022-06-15'), 50.123, 50.123,
				50.123, 50.0, 0, 0,
				CLOB('filtered text'), BLOB(X'00'),
				TIMESTAMP('2022-06-15-10.00.00.000000'),
				TIME('10.00.00'),
				GRAPHIC('filtered'),
				VARGRAPHIC('filtered'),
				FALSE,
				200
			)`, integrationTestTable)
		err = exec(ctx, db, filteredQuery)
		require.NoError(t, err, "Failed to insert filtered test data row")
		return

	case "insert_2pc":
		query = fmt.Sprintf(`
			INSERT INTO %s (
				col_cursor, col_bigint, col_char, col_character,
				col_varchar, col_date, col_decimal, col_decfloat,
				col_double, col_real, col_int, col_smallint,
				col_clob, col_blob, col_timestamp, col_time,
				col_graphic, col_vargraphic, col_bool
			) VALUES (
				7, 12345678901234, 'c', 'char_val',
				'varchar_val', DATE('2023-01-01'), 123.45, 123.45,
				123.456789, 123.5, 123, 123,
				CLOB('sample text'), BLOB(X'424C4F422044415441204F4E45'),
				TIMESTAMP('2023-01-01-12.00.00.000000'),
				TIME('12.00.00'),
				GRAPHIC('graphic_val'),
				VARGRAPHIC('vargraphic_val'),
				TRUE
			)`, integrationTestTable)

	case "update":
		query = fmt.Sprintf(`
        UPDATE %s SET
            col_cursor = NULL,
            col_smallint = 321,
			col_timestamp = TIMESTAMP('2024-01-01-12.00.00.000000'),
			excludedColumn = 102,
			includedColumn = 202
        WHERE id = 1`, integrationTestTable)

	case "delete":
		query = fmt.Sprintf("DELETE FROM %s WHERE id = 1", integrationTestTable)

	case "evolve-schema":
		evolveQuery := fmt.Sprintf(`ALTER TABLE DB2INST1.%s ALTER COLUMN COL_SMALLINT SET DATA TYPE BIGINT`, integrationTestTable)
		err = exec(ctx, db, evolveQuery)
		require.NoError(t, err, "Failed to execute %s operation", operation)
		// Add new column
		addColumnQuery := fmt.Sprintf(`ALTER TABLE DB2INST1.%s ADD COLUMN includedColumn INTEGER`, integrationTestTable)
		err = exec(ctx, db, addColumnQuery)
		require.NoError(t, err, "Failed to execute %s operation", operation)

		// to clear REORG pending state of DB2 after schema evolution
		query = fmt.Sprintf(`CALL SYSPROC.ADMIN_CMD('REORG TABLE DB2INST1.%s')`, integrationTestTable)

	case "populate-stats":
		// if table exists, run stats for DB2 to populate stats
		query = fmt.Sprintf(`CALL SYSPROC.ADMIN_CMD('RUNSTATS ON TABLE DB2INST1.%s AND INDEXES ALL')`, integrationTestTable)

	default:
		t.Fatalf("Unsupported operation: %s", operation)
	}

	err = exec(ctx, db, query)
	require.NoError(t, err, "Failed to execute %s operation", operation)

	if operation == "clean" {
		requireEmptyTable(ctx, t, db, integrationTestTable, operation)
	}
}

// requireEmptyTable fails when a reset left rows behind, at the operation that caused it.
func requireEmptyTable(ctx context.Context, t *testing.T, db *sqlx.DB, table, operation string) {
	t.Helper()
	var rows int
	require.NoError(t, db.GetContext(ctx, &rows, fmt.Sprintf("SELECT COUNT(*) FROM %s", table)),
		"failed to count rows after %s", operation)
	require.Zerof(t, rows, "%s left %d rows in %s", operation, rows, table)
}

func insertTestData(ctx context.Context, t *testing.T, db *sqlx.DB, tableName string) {
	t.Helper()

	for i := 1; i <= 5; i++ {
		query := fmt.Sprintf(`
		INSERT INTO %s (
			col_cursor, col_bigint, col_char, col_character,
			col_varchar, col_date, col_decimal, col_decfloat,
			col_double, col_real, col_int, col_smallint,
			col_clob, col_blob, col_timestamp, col_time,
			col_graphic, col_vargraphic, col_bool, excludedColumn
		) VALUES (
			%d, 12345678901234, 'c', 'char_val',
			'varchar_val', DATE('2023-01-01'), 123.45, 123.45,
			123.456789, 123.5, 123, 123,
			CLOB('sample text'), BLOB(X'424C4F422044415441204F4E45'),
			TIMESTAMP('2023-01-01-12.00.00.000000'),
			TIME('12.00.00'),
			GRAPHIC('graphic_val'),
			VARGRAPHIC('vargraphic_val'),
			TRUE,
			100
		)`, tableName, i)

		require.NoError(t, exec(ctx, db, query), "Failed to insert test data")
	}
	// insert a filtered row — timestamp is before the filter threshold, so it won't be synced
	filteredQuery := fmt.Sprintf(`
		INSERT INTO %s (
			col_cursor, col_bigint, col_char, col_character,
			col_varchar, col_date, col_decimal, col_decfloat,
			col_double, col_real, col_int, col_smallint,
			col_clob, col_blob, col_timestamp, col_time,
			col_graphic, col_vargraphic, col_bool, excludedColumn
		) VALUES (
			-1, 111111111111111, 'x', 'filtered',
			'filtered_val', DATE('2021-06-15'), 500234.123, 500234.123,
			500234.123, 500234.0, 0, 0,
			CLOB('filtered text'), BLOB(X'00'),
			TIMESTAMP('2021-06-15-10.00.00.000000'),
			TIME('10.00.00'),
			GRAPHIC('filtered'),
			VARGRAPHIC('filtered'),
			FALSE,
			200
		)`, tableName)
	require.NoError(t, exec(ctx, db, filteredQuery), "Failed to insert filtered test data row")
}

var ExpectedDB2Data = map[string]interface{}{
	"col_bigint":     int64(12345678901234),
	"col_char":       "c",
	"col_bool":       true,
	"col_character":  "char_val",
	"col_varchar":    "varchar_val",
	"col_date":       arrow.Timestamp(time.Date(2023, 1, 1, 0, 0, 0, 0, time.UTC).UnixNano() / int64(time.Microsecond)),
	"col_decimal":    float64(123.45),
	"col_decfloat":   "123.45",
	"col_double":     123.456789,
	"col_real":       float32(123.5),
	"col_int":        int32(123),
	"col_smallint":   int32(123),
	"col_clob":       "sample text",
	"col_blob":       "BLOB DATA ONE",
	"col_timestamp":  arrow.Timestamp(time.Date(2023, 1, 1, 12, 0, 0, 0, time.UTC).UnixNano() / int64(time.Microsecond)),
	"col_time":       "12:00:00",
	"col_graphic":    "graphic_val",
	"col_vargraphic": "vargraphic_val",
}

var ExpectedUpdatedDB2Data = map[string]interface{}{
	"col_bigint":     int64(12345678901234),
	"col_char":       "c",
	"col_character":  "char_val",
	"col_bool":       true,
	"col_varchar":    "varchar_val",
	"col_date":       arrow.Timestamp(time.Date(2023, 1, 1, 0, 0, 0, 0, time.UTC).UnixNano() / int64(time.Microsecond)),
	"col_decimal":    float64(123.45),
	"col_decfloat":   "123.45",
	"col_double":     123.456789,
	"col_real":       float32(123.5),
	"col_int":        int32(123),
	"col_smallint":   int64(321),
	"col_clob":       "sample text",
	"col_blob":       "BLOB DATA ONE",
	"col_timestamp":  arrow.Timestamp(time.Date(2024, 1, 1, 12, 0, 0, 0, time.UTC).UnixNano() / int64(time.Microsecond)),
	"col_time":       "12:00:00",
	"col_graphic":    "graphic_val",
	"col_vargraphic": "vargraphic_val",
	"includedcolumn": int32(202),
}

var DB2ToDestinationSchema = map[string]string{
	"id":             "bigint",
	"col_cursor":     "bigint",
	"col_bigint":     "bigint",
	"col_char":       "string",
	"col_character":  "string",
	"col_bool":       "boolean",
	"col_varchar":    "string",
	"col_date":       "timestamp",
	"col_decimal":    "double",
	"col_decfloat":   "string",
	"col_double":     "double",
	"col_real":       "float",
	"col_int":        "integer",
	"col_smallint":   "integer",
	"col_clob":       "string",
	"col_blob":       "string",
	"col_timestamp":  "timestamp",
	"col_time":       "string",
	"col_graphic":    "string",
	"col_vargraphic": "string",
}

var UpdatedDB2ToDestinationSchema = map[string]string{
	"id":             "bigint",
	"col_cursor":     "bigint",
	"col_bigint":     "bigint",
	"col_char":       "string",
	"col_character":  "string",
	"col_bool":       "boolean",
	"col_varchar":    "string",
	"col_date":       "timestamp",
	"col_decimal":    "double",
	"col_decfloat":   "string",
	"col_double":     "double",
	"col_real":       "float",
	"col_int":        "integer",
	"col_smallint":   "bigint",
	"col_clob":       "string",
	"col_blob":       "string",
	"col_timestamp":  "timestamp",
	"col_time":       "string",
	"col_graphic":    "string",
	"col_vargraphic": "string",
	"includedcolumn": "integer",
}
