name: Go Build and Lint
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "*"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"

      - name: Cache driver external dependencies
        uses: ./.github/actions/driver-deps
        with:
          save: "true"

      - name: golangci-lint
        run: make olake.lint

  build-check:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v4
        with:
          go-version-file: "go.mod"
      - name: Run build
        run: make build
